title: Daniel Lipsey
email: dlipsey@bu.edu
description: >- # this means to ignore newlines until "baseurl:"
  Home
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dlipsey.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dlipsey
github_username:  dlipsey

# Build settings
theme: minima
plugins:
  - jekyll-feed
