title: Daniel Lipsey
email: dlipsey@bu.edu
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dlipsey.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: jekyll-theme-modernist
plugins:
  - jekyll-feed
