project:
  type: website

website:
  sidebar:
    style: "docked"
    search: false
    header: |
     ![](DL.JPEG){class="rounded" style="width:10em;"}
     **Daniel Lipsey**
     
     Applied health economics
     Health services research

    contents:
     - index.qmd
    
    
   



format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false



